package nl.bioinf.demultiplexer;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class FastQReadTest {

    public static List<FastQRead> fastQReads (){
        List<FastQRead> fastQReads = new ArrayList<>();

        fastQReads.add(new FastQRead("@27e9d0c4-3ebc-44e5-af8d-9c9f9ba0e3f2 runid=6b09fdca36079d24f1ff5f71c12949d4702e6f9d sampleid=predica1 read=214768 ch=139 start_time=2022-11-25T20:54:13Z model_version_id=dna_r10.4.1_e8.2_260bps_hac@v3.5.2".toCharArray(),
                "TGAACAGCATCGATTGGATTTGGACTTAGAGTTAATTCTGAAATGAATTAAGTCTTTGGAGTAATTGTTGGAAAGGCATGATTGGGTTTTAAAATGTGAGGATGTAAGATTTCAGAGGGGGCAGGGGCAGAATGATATGGTTTGGCTGTATACCCACCAAAATCTAATCTTGTAGTTCCCATGATCGCCACATATCATGAGAGGGACCCCGTAGGAAGTAATGTAATCAGGGGGGCAGCCCGTGGCAGGACTTTTGAGGATATCACACGGGCCTTTGAAGGGCAGGCACACGGTGCAGATAGATCTGGAAAGGACGGCGTCATGA".toCharArray(),
                "+".toCharArray(),
                "#'),/))))*(&((+--11012?><;A@AC@BCBDDB@@>>?/--.;=9<=<7,**(&&(1:;?@D@==?@AB@A@@A?>>?@ADCF>=<688;A@BBBDEBA@=95/-/)*569;=?>?AC@>84+(''(%##%&&(+/67E<555A@?>@BDEEHE;655?521/2-+-+(%%%##$)0056=CBDEFKIC:9=<=:9:9A@@?=<<;==:;<<@>=?ADEFEHJIIDCBCCCE@@?@@?@ACDBA@ABBFMIB@><<<AFD@?A?A@@??ACF?9977:811322486@?@A?8631-**,-.@>?EMOCA?>>=;;;<?.%".toCharArray()));

        fastQReads.add(new FastQRead("@f4bd9990-0383-48fc-9325-46d5cbb4886f runid=6b09fdca36079d24f1ff5f71c12949d4702e6f9d sampleid=predica1 read=142985 ch=466 start_time=2022-11-25T20:54:35Z model_version_id=dna_r10.4.1_e8.2_260bps_hac@v3.5.2".toCharArray(),
                "ATGTTATGGTTACCTTGGTTTCAGTTCGGTCTTGCTAATGATACAGCAACCACCGAGATCTACACTATTCGATCTATACGAGATCCGTAATCGGGAAGCTGAAGCCAAACTCTTCATTCATCAACCAAATTGCCAGCTTGGTTGTTGTTACCTTTTGCTTATTATATATATTACATGATTCCATTTATGTGAAAGGTCCAGAATAGTCAAATCTATAGAGGCAGAAAGCAGGTAAGTGGTTGCCAGGAGCTGGGGGAAAGGGGAGGCTACCGTCGGATCGTGCGTGTCGTCTGAGTTATCTCGTATGCCGTCTTCTGCTTGAGCAATACATA".toCharArray(),
                "+".toCharArray(),
                "$#$'*''%##%#$$#&')'()''&&'%&'&)***?@AEGFED@>000-++15@@::??@AGBABACDDHF>>><>;;=====@@?@;=<=GCA>@GG=::;DDCBCABCCCCCGMGECACCBECBB=>D=BBCAB@@A@ACH=<=@HEABBCC@BABC;;;8:::989B?F>@DC@@??@>>=AA?>>>C?;;=BD@;5D?@DEH@><6445FFDDDEC??<;=@LG><<=<;;;<<<<BAA@?@@DD>>@NBJGGFHD>==@FGEA@=;:9:<><<=@;:::=>>C=;::@--,-4?J8863568542-,&'.04?=>><==<5556:41'".toCharArray()));

        fastQReads.add(new FastQRead("@cd597a21-dfe7-40ed-b8e0-81f21a1ff714 runid=6b09fdca36079d24f1ff5f71c12949d4702e6f9d sampleid=predica1 read=123152 ch=191 start_time=2022-11-25T20:54:05Z model_version_id=dna_r10.4.1_e8.2_260bps_hac@v3.5.2".toCharArray(),
                "ATGTACATCTACTGGTTCGGTTGCGTATTGCTAATGATACGGCGACCACCGAGATCTACACCACGGCATATACAAGATGCGGCGTGGGAAGCTGAAGCGCACTTCCATCCAGAAGAGAGCAGCATCAATCCCTTCCTCTCACACTACCGTCGGATCGTGCGTGTGAAGAGTATTATCTCGTATGCCGTCTTCTGCTTGAGCAATACATTGTTATGTTTTGTTGTATTTATTCATTCGTCGTATTGCTAATGATACGGCGACCGCCGAGATCTACACACTGGATGCTATACGAGATCCGTAATCGGGAAGCTGAAGGCTGCCCCAGCCACCACCATCTCTTACTTCAGCTACTACGATAGACTCTACACTGGTAACCAGAGATGTCTTTTTATAATATAATTCAGAACATATAGCTCACGCTTAGGACATTTCAACAGTTTCCATTGTTCCCAGATGGCGACTAATAATTTCGATGTCTACCGTCGGATCGTGCGTGTCTAAGAGTTAATCTCGTATGCCGTCTTCTGCTTGAGCGATACGT".toCharArray(),
                "+".toCharArray(),
                "\"#%%$##\"###$%##%%%###$*'''*669AA@@?8974+***8453/,,+333:6655-**'('&+*++/,**))(,((%%###'.99ABDC<;;;ECG?<:;=CA93>0??=45*.;,,,=>A><<;99ECD4658582235=<@9***9;ACB@>>>><<<@CCEEEDDDGFECB@>A@A@<<<>CCCCDDBC8../40/0//,,+&%%#&%'*,)'&&$##$%%%$%$$%%&%%%%&)(()3678?=>><=-,-----'')(,++,,/--.-{2//29;</---661++,,,@=@?AD4001<ACAA?BDFGBDDBCCDAE@ECB?>@@CBBC?@D53377768+)((*21100,.>@FEEHEFIDBCABBC??@GDFBCGHDCBADGEEBA@?@@>A=>?BCGGHKDCFEFEBA=<<<GCBCBEEHEGGKFKNB@>>==???<<;>??:4.1(.,)(((/1276/.(&'((+,+./&&%%)(03//,+**-09:;<=@FHC@AFAA?<=>@D?=<<>?CABA><@-,,3)(((4,)".toCharArray()));

        fastQReads.add(new FastQRead("@a502c2b3-605b-4788-9bc3-22b0774089e8 runid=6b09fdca36079d24f1ff5f71c12949d4702e6f9d sampleid=predica1 read=108977 ch=407 start_time=2022-11-25T20:54:19Z model_version_id=dna_r10.4.1_e8.2_260bps_hac@v3.5.2".toCharArray(),
                "TATGTTATGGTTCTTGGTTCGTTACGTATTGCTAATGATACGACCCACCGAGATCTACACTGCGCGATGACCGAGATCCGTAATCGGGAAGCTGGAGTCAGCCAGAGGATGCCTCTCTTGCTCTGGGCCTCGTCGCCCACATAGGAATCCTTCTGACCCATGCCCACCATCACGCCCTGGTGCCTGGGCGCCCCACGAGATGGAGGGGAAGACGGCCCGGGGGGCATCGTCGCCCGCGAAGCCGGCCTTGCACATGCACACTACCGTCGGATCGTGCGTGTCAGCGAACTTATCTCGTATGCCGTCTTCTGCTAGCAATACGTTATCATTGTTACTTCGTTCAGTTACGTATTGCTCAAGCAGAAGACGGCATACGAGATCTGAACTGGTACACGCACAATACCGACGGTAGTGTACCACAGACAGGAAAGAGCAGGCCTGGAAAATGAGTTCAACTACATCAGACTGGGATGCTCATGTAGGAAAATAGTAAGAAAACAGCAAGAAGGTACTAAGTGAGCCATGGCGTCACACACAGGTTTTCATTTTACCCCTCACTGGCAAGGTAAGGTCTTCAGCTTCCCGATTACGGATCTCGTATCCTTCCTTCAGTGTAGATCTCGGTGGTCGCCGTACTCGTCACAATACGTGGTTATGTTATTGTACTTGGTTCGTTACGTATTGCTAATGATACAGCAACCACCGAGATCTACACTAACTCTTAGATACGAGATCCGTAATCGGGAAGCTGAAGCCATAACTTTGGTGGTGGTCTCCTTAGCAGGCTCAATGCTGTTCATCTCCATGACGCCGTCCTTTCCAGATCTATCTGCACCGTGTGCCTGCCCTTCAAAGGCCCGTGTGATATCCTCAAAAGTCCTGCCACGGGTCTCAGGGACTGAAGAAGGTAAACACTACCGTCGGATCGTGCGTGTAGCATCCAGTATCTCGTATGCCGTCTTCTGCTTGGAATGCGTAATGTCCTAACTTACTTCGTTCAGTTACGTATTGCTCAAGCAGAAGACGGCATACGAGATACGCAATGATACGCGCACAATCCAAGCAGGTAGTGTGCATGTGCAAGGCCGGCTTCGCGGGCGACGAGATCCCCGGGCCGTCTTCCCCTCCATCGTGGGGCGCCCCAGGCACCAGGGCGTGATGGTGGGCATGGGTCAGAAGGATTCCTATGTGGGCGACGAGGCCCAGAGCAAGAGAGGCATCCTAAAGCTCACTTCAGCTTCCGATTACGGATCTCGTATGAATATCATAGTGTAGATCTCGGTGGTCGCCGTATCATAAGCAATACGTCCTCTACTCAACAACTCGTATTGCTAATGATACGGCGACCACCAAGATACACTATTCGATCTATACGAGATCCGTAATCGGGAAGCTGAAGGGCCTACCCGTTATCGCTGACTTTCCAGATCAGGGTCAGGCTTGTGGCACTGATGTTCACAGCGGTGACGTCAAAAACCTGAATAGCATTTGTCCTGAACTCTATGGCCTGGGGCTGTCCTTCTGTGTCATTCGCTGCTTGGGAATAAACGGTGGCATACACTACCGTCGGATCGTGCGTGTCGTCTGAGTTATCTCGTATGCCGTCTTCTGCTTCAGCAATACGTAGTGTTATGTAACCGTTTGACAGATTACGTATTGCTCAAGCAGAAGACGGCATACGAGATTGCGCGATGCACACGCACGATCCGACGGTAGTGGCAGCAACGAAGTATCCTCTCCTGAAATTTGGTAATACTTCAGCTTCCCGATTAGGAGACTCGTATCAGCGAACTTGTGTAGATCTCGGTGGTCGCCGTATCATTAGCAATACG".toCharArray(),
                "+".toCharArray(),
                "'$$)*+))*###\"##&*=<91114334?AAA=??@E976,)%)*+1069011:C:?67:6444;=))))'$$%%)*15<7>?AD?::=@GDCBD<;<::;<<?DA@@?AAED@@<A{A?;A@A@BB=???=888:>:;++++<<<=CABD5955@GJBA@ADABC8888A<;9::@@BC>>;533'&)0))*)*&(('%%%79@CAHIMLGD<*))*.)=?@Q<334;0.,-6799>453-+++,,/=?.-/018>BCC1//0>=783/-.<@?A=<;;<=DDEC?@AADDCCDB;89;AC@?>99DDC@?><,&%&&'))(&$$$#\"$%&+.,*++*333AA><==?===ABCDEDFEHIFFGHB@8799:@CB@?==>=B@BGCA>;<<===;:43((('%%%*-113CD@??CCD@==@>EDDKBCC?<;@>621311=<A;<3>;>=77775*''6690++99:9:<=@DHEFDFBA@>=<<=@FEAAAABA@@A8679;AFDDGIJ;99<<;;;<?JDC@>=<=??FFEDGFB=99;;;<;?@AL?=<>?@A>??>AAAEB@AAB@??BDFB?=<@@?D?CCCBC665:973135:CA@A??@BBD@???B@BB@@@>@B@>==<==ABB<65020,+))%+''')(%$$%&'(##$%(('(+'+-04-,,3333=@?@>@ABDEEEDG0000001<<=<>@??<?>BB?@@@DE@@)&'))*=???BDA?<ACGKHDC;?AAA?>=;<<<:<<>777>7?BCCCD??>>A<7?(&&'&%$#$'')2988:@:;A@ECACCCC??>>@BBDCDE@KFEHHDDCADIGHFD@===@?==??@@@ABDGKKNB?>9888BEBDBEA==>>@BOL<<;@????===<C@ACA<45/8+()77E==A;::<EA@A===;;:<<=AFBBA@@???@BB@@<?98557>?=;@@AFCA@AABB?@@?A:'$$&'**)+%$$##\"##%%'())-31..57;987;77766799:@@CFJIFCCB=D@>>>AEGDB@?@??C@@@AAAAADD('''98...,+*+-.2;=?@@A?BK>>ABBDDDIBA?=??=@B@===@??@@@;:(((-'(-8A@?>>?@DEA?===@>???;;:?>??===?EB@@?BEFFBAAA==>>BCCBBCBCBB7769;<?HHD<=9?A@>>ACECBAA=::8::=B@?@6103BHIL\\{OFEDEHGFDACFBC@>===?CA?@/47(;;><7223440(()*666ABFEEDCA>>>@BCCBAADCCDE@??<=<:;;9/..&&'*-11+((($&''%$$&$$$#$'&(%&/.///?@?@BEHEFB?>>?A@ECDB,'')&%&77;>;<21155600==@=<<?BBBCEFRJFDAEFBAABCBB>?===>>B@@CCGNFBAADDBBBJFEB@@@BC?>>BCEDDEDEEDDBA@>?@ACCDEFMHF>;::?@FB;899EFGGDCFEHHEEDCGHKHF@?>?BFGFEA??=>=>BDCDCDAA@CCAA@>=>@O,(((<A6444420+,<DEFBDD@;;;AC?>><>>?AA@@>???>?@A=<=???>BBBBBDCBBBA::44449:<DA?<<=>F??0,+-)+++>>?>?88(%###'%&&%##$$%%&(()()(((()+,,2AACFGFEA=>HBBB<B?>?@@BEDBB<<<=BAAB@>>?@ABIC??@?9888A?>=:::<@>=<=====?D====AABG???{A>??A@MQ{LH???@GD?>>=@>>==:/,(,)+($%&*%%%%&323.,,,34?>@=:<=BIFHGFHFA??@@A=999<>?CCAABC>===A@:.".toCharArray()));

        fastQReads.add(new FastQRead("@44a1cf6f-fa88-4d88-a7a7-910edc597fac runid=6b09fdca36079d24f1ff5f71c12949d4702e6f9d sampleid=predica1 read=107067 ch=413 start_time=2022-11-25T20:54:12Z model_version_id=dna_r10.4.1_e8.2_260bps_hac@v3.5.2".toCharArray(),
                "GTTGTGTTATGTCTTGTATTTCGTTCAGTTACGTATTGCTAATGATACGGCGACCACCGAGATCTTCACTATTCGATCTATACGAGATCCGTAATCGGGAAGCTGAAGCGCAAACCGTTTAGCTTTCTTTTTATTTTTTAATTACCCTAAAGTGAAGGAGCACATAATTCATTGGGTGGGTCAAGGAAAACCAAAAGGCCTGAAGATCAATAACGTTAGCTTACAGAAGTCATTCTGTAATACCATTTAATTGTGTAAACTTGGGCCTTATACCGTCGGATCGTGCGTGTCGTCTGAGTTATCTCGTATGCCGTCTTCTGCTTGAGCAATACAT".toCharArray(),
                "+".toCharArray(),
                "%%&&&'-001,)%$#\"$'%%&)589@?>=@===<AKHG>>>>C''''@>=><<<<A?@;;<:?7/.***7;=@:64433//22==<<>?ECDFFMIB?=@A@@@ABFEAAAEGHEBBCDDDF???>@<;658<7;ABCD@BDAAAA@??>CDCDCDCADCEI>9888877*/-'258?HIDA?@CCDDDA?>>><::>@@???BF???@IEC==>?@@>?;<<=B>;;=KO?==??B@A@@>>?@@@><4-+32483??C@A@;99<ACBB??*(('..0940005@@AC?;;<DFBBBDA?::6.///>?=<=>>@?A@=;=4677((((5,(".toCharArray()));
        return fastQReads;
    }

    @Test
    void testToString() {
        List<FastQRead> myList = fastQReads();

        for (FastQRead fastQRead : myList) {
            System.out.print(fastQRead.toString());
        }



    }
}